<?php
// Generate JavaScript code that will inject the tool history dropdown into the response modal
$js_code = "";
$js_code .= "// Tool Call History Injection Script\n";
$js_code .= "(function() {\n";
$js_code .= "    // Function to create the tool history HTML\n";
$js_code .= "    function createToolHistoryPanel() {\n";
$js_code .= "        var historyHtml = '<div class=\"tool-history-panel\" style=\"border: 1px solid #e0e0e0; border-radius: 8px; margin-bottom: 20px; background-color: #f9f9f9;\">';\n";
$js_code .= "        historyHtml += '<h3 style=\"margin: 0; padding: 12px 16px; background-color: #f0f0f0; border-bottom: 1px solid #e0e0e0; font-size: 16px; font-weight: 600;\">Tool Call History</h3>';\n";
$js_code .= "        historyHtml += '<div style=\"padding: 16px;\">';\n";
$js_code .= "        historyHtml += '<details style=\"margin-bottom: 12px; border-left: 4px solid #2196F3; padding-left: 12px;\">';\n";
$js_code .= "        historyHtml += '<summary style=\"cursor: pointer; font-weight: 600; color: #2196F3;\">Click to view tool call history</summary>';\n";
$js_code .= "        historyHtml += '<div id=\"tool-history-content\" style=\"margin-top: 12px; padding: 12px; background-color: white; border-radius: 4px; border: 1px solid #e0e0e0;\">';\n";
$js_code .= "        historyHtml += '<p style=\"color: #666; font-style: italic;\">Loading tool call history...</p>';\n";
$js_code .= "        historyHtml += '</div>';\n";
$js_code .= "        historyHtml += '</details>';\n";
$js_code .= "        historyHtml += '</div>';\n";
$js_code .= "        historyHtml += '</div>';\n";
$js_code .= "        return historyHtml;\n";
$js_code .= "    }\n";
$js_code .= "\n";
$js_code .= "    // Function to load and display tool history\n";
$js_code .= "    function loadToolHistory() {\n";
$js_code .= "        // Use the existing show_tool_call_history tool via AJAX\n";
$js_code .= "        $.ajax({\n";
$js_code .= "            url: '/MemoryGraph/api/tool_call.php',\n";
$js_code .= "            type: 'POST',\n";
$js_code .= "            data: { tool: 'show_tool_call_history' },\n";
$js_code .= "            success: function(response) {\n";
$js_code .= "                try {\n";
$js_code .= "                    var data = JSON.parse(response);\n";
$js_code .= "                    if (data.html) {\n";
$js_code .= "                        $('#tool-history-content').html(data.html);\n";
$js_code .= "                    }\n";
$js_code .= "                } catch(e) {\n";
$js_code .= "                    console.error('Error parsing tool history response:', e);\n";
$js_code .= "                }\n";
$js_code .= "            },\n";
$js_code .= "            error: function(xhr, status, error) {\n";
$js_code .= "                console.error('Error loading tool history:', error);\n";
$js_code .= "                $('#tool-history-content').html('<p style=\"color: #d32f2f;\">Failed to load tool history: ' + error + '</p>');\n";
$js_code .= "            }\n";
$js_code .= "        });\n";
$js_code .= "    }\n";
$js_code .= "\n";
$js_code .= "    // Inject the tool history panel into the response modal\n";
$js_code .= "    function injectToolHistory() {\n";
$js_code .= "        // Check if the response modal body exists\n";
$js_code .= "        var $modalBody = $('#response-modal-body');\n";
$js_code .= "        if ($modalBody.length === 0) {\n";
$js_code .= "            console.warn('Response modal body not found');\n";
$js_code .= "            return;\n";
$js_code .= "        }\n";
$js_code .= "\n";
$js_code .= "        // Create the tool history panel\n";
$js_code .= "        var historyPanel = createToolHistoryPanel();\n";
$js_code .= "\n";
$js_code .= "        // Insert at the top of the modal body\n";
$js_code .= "        $modalBody.prepend(historyPanel);\n";
$js_code .= "\n";
$js_code .= "        // Load the actual tool history content\n";
$js_code .= "        loadToolHistory();\n";
$js_code .= "    }\n";
$js_code .= "\n";
$js_code .= "    // Wait for the DOM to be ready\n";
$js_code .= "    $(document).ready(function() {\n";
$js_code .= "        // Inject tool history when the response modal is shown\n";
$js_code .= "        $(document).on('shown.bs.modal', '#response-modal', function() {\n";
$js_code .= "            injectToolHistory();\n";
$js_code .= "        });\n";
$js_code .= "\n";
$js_code .= "        // Also inject when new responses are loaded\n";
$js_code .= "        $(document).on('chatResponseLoaded', function() {\n";
$js_code .= "            injectToolHistory();\n";
$js_code .= "        });\n";
$js_code .= "    });\n";
$js_code .= "})();\n";

// Return the JavaScript code
$result = ['js_code' => $js_code];
echo json_encode($result);
?>